language: python
sudo: required
dist: xenial
python:
  - "3.6"
  - "3.7"
env:
  - draft07=false
  - draft07=true
install:
  - pip install --upgrade pip setuptools twine
  - pip install -r requirements.txt
  - test $draft07 && pip install --upgrade --pre jsonschema
  - pip install .
script:
  - source check.sh
  - git diff --exit-code
jobs:
  include:
    - stage: publish
      if: branch = master AND repo = Zac-HD/hypothesis-jsonschema
      script: python setup.py sdist && twine upload --skip-existing dist/*
